version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_db
    ports:
      - "6000:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
        POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    hostname: postgres

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
    hostname: mongodb

  couponservice:
    image: csharpjanari/couponservice:latest
    container_name: couponservice
    hostname: couponservice
    ports:
      - 3010:3010

volumes:
  postgres_data:
  mongodbdata:
