FROM node:18.16-alpine

WORKDIR /app

COPY src/backend/authService/package.json src/backend/authService/package-lock.json ./
COPY src/backend/authService/. .            

RUN npm install -g typescript && npm ci
RUN npm run build

ENV NODE_ENV=production
ENV MONGO_URL=mongodb://mongodb:27017/auth
ENV PORT=3020

EXPOSE ${PORT}

CMD ["npm", "run", "start"]