version: "3.8"

services:
  nginx:
    image: nginx:1.25.2-alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80

  # Frontend
  restaurant_frontend:
    image: csharpjanari/restaurant_frontend
    container_name: restaurant_frontend
    hostname: restaurant_frontend
    ports:
      - 3000:3000

  # Services
  authservice:
    image: csharpjanari/authservice:latest
    container_name: authservice
    hostname: authservice
    ports:
      - 3020:3020

  couponservice:
    image: csharpjanari/couponservice:latest
    container_name: couponservice
    hostname: couponservice
    ports:
      - 3010:3010

  productservice:
    image: csharpjanari/productservice:latest
    container_name: productservice
    hostname: productservice
    ports:
      - 3030:3030

  shoppingcartservice:
    image: csharpjanari/shoppingcartservice:latest
    container_name: shoppingcartservice
    hostname: shoppingcartservice
    ports:
      - 3040:3040

  # Databases
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/restaurant/mongodb
    hostname: mongodb

  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3307:3306
    volumes:
      - mysqldata:/data/restaurant/mysql

volumes:
  mongodbdata:
  mysqldata:
