version: "3.8"

services:
  # Frontend
  restaurant_frontend:
    image: csharpjanari/restaurant_frontend
    container_name: restaurant_frontend
    hostname: restaurant_frontend
    ports:
      - 3000:3000

  # Services
  couponservice:
    image: csharpjanari/couponservice:latest
    container_name: couponservice
    hostname: couponservice
    ports:
      - 3010:3010

  # Databases
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
    hostname: mongodb

volumes:
  mongodbdata:
